site_name: ELIXIR FAIR Lesson Plans
site_url: https://elixir-europe-training.github.io/ELIXIR-TrP-FAIR-Converge

nav:
    - Home: index.md
    - About: 
      - "Contributors": "about/contributors.md"
      - "Support": "about/support.md"
    - Contribute:
        - "How to contribute": "contribute/how_to_contribute.md"
        - "Style guide": 'contribute/style_guide.md'
    - Lesson plans:
      - "1. FAIR generics": 
        - "Overview": 'units/FAIR-generics/index.md'
        - 'units/FAIR-generics/topics/1-why-fair.md'
        - 'units/FAIR-generics/topics/2-FAIR-vs-open-data.md'
        - 'units/FAIR-generics/topics/3-data-life-cycle-and-FAIR-from-start.md'
        - 'units/FAIR-generics/topics/4-FAIR-in-data-policies.md'
        - 'units/FAIR-generics/topics/5-defining-FAIR-objectives-for-projects.md'
        - 'units/FAIR-generics/topics/6-FAIR-objectives-for-organisations.md'
        - 'units/FAIR-generics/topics/7-policies-and-consent.md'
      - "2. Findable data":
        - "Overview": 'units/findable-data/index.md'
        - 'units/findable-data/topics/1-data-and-repository-discovery.md'
        - 'units/findable-data/topics/2-persistent-identifiers.md'
        - 'units/findable-data/topics/3-metadata-standards.md'
      - "3. Accessible data":
        - "Overview": 'units/accessible-data/index.md'
        - 'units/accessible-data/topics/1-data-access.md'
      - "4. Interoperable data":
        - "Overview": 'units/interoperable-data/index.md'
        - 'units/interoperable-data/topics/1-linked-data-and-semantic-web.md'
        - 'units/interoperable-data/topics/2-M4M-workshop.md'
        - 'units/interoperable-data/topics/3-vocabularies-and-ontologies.md'
      - "5. Reusable data":
        - "Overview": 'units/reusable-data/index.md'
        - 'units/reusable-data/topics/1-FAIR-data-visiting.md'
      - "6. FAIR software":
        - "Overview": 'units/FAIR-software/index.md'
        - 'units/FAIR-software/topics/1-FAIR-software.md'
      - "7. Data Repositories and FAIR":
        - "Overview": 'units/data-repositories/index.md'
        - 'units/data-repositories/topics/1-repositories-and-FAIR.md'
theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
    - content.action.edit
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-FAIR-Converge
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-FAIR-Converge
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  - mkdocs-video # embed videos to the docs
  - include-markdown
  - markdownextradata
  - macros:
      include_yaml:
        - contributors: _data/contributors.yaml
        - fair_principles: _data/fair_principles.yaml
        - levels: _data/levels.yaml
  - site-urls
  
# Footer
copyright: By the ELIXIR Training Platform

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - neoteroi.cards
  - md_in_html

extra:
  status:
    ready_for_review: "Ready for review"
    in_progress: "In progress"
    published: "Published"

extra_css:
  - stylesheets/skeleton.css
  - stylesheets/extra.css
  - stylesheets/lesson-plans.css
  - stylesheets/neoteroi-mkdocs.css
  - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200
